export const CREATE_USER_REQUEST: 'CREATE_USER_REQUEST' = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS' = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR: 'CREATE_USER_ERROR' = 'CREATE_USER_ERROR';
export const RESET_PASSWORD: 'RESET_PASSWORD' = 'RESET_PASSWORD';

export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST' = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS' = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR: 'CREATE_ORDER_ERROR' = 'CREATE_ORDER_ERROR';

export const SET_SELECTED_INGREDIENT: 'SET_SELECTED_INGREDIENT' = 'SET_SELECTED_INGREDIENT';
export const CLEAR_SELECTED_INGREDIENT: 'CLEAR_SELECTED_INGREDIENT' = 'CLEAR_SELECTED_INGREDIENT';

export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const MOVE_CARD: 'MOVE_CARD' = 'MOVE_CARD';
export const CLEAR_ADDED_INGREDIENTS: 'CLEAR_ADDED_INGREDIENTS' = 'CLEAR_ADDED_INGREDIENTS';

export const GET_INGREDIENT_REQUEST: 'GET_INGREDIENT_REQUEST' = 'GET_INGREDIENT_REQUEST';
export const GET_INGREDIENT_SUCCESS: 'GET_INGREDIENT_SUCCESS' = 'GET_INGREDIENT_SUCCESS';
export const GET_INGREDIENT_ERROR: 'GET_INGREDIENT_ERROR' = 'GET_INGREDIENT_ERROR';

export const WS_USER_CONNECTION_START: 'WS_USER_CONNECTION_START' = 'WS_USER_CONNECTION_START';
export const WS_USER_CONNECTION_SUCCESS: 'WS_USER_CONNECTION_SUCCESS' = 'WS_USER_CONNECTION_SUCCESS';
export const WS_USER_CONNECTION_CLOSED: 'WS_USER_CONNECTION_CLOSED' = 'WS_USER_CONNECTION_CLOSED';
export const WS_USER_CONNECTION_ERROR: 'WS_USER_CONNECTION_ERROR' = 'WS_USER_CONNECTION_ERROR';
export const WS_USER_GET_MESSAGE: 'WS_USER_GET_MESSAGE' = 'WS_USER_GET_MESSAGE';

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';

export const GET_FOUND_ORDER_REQUEST: 'GET_FOUND_ORDER_REQUEST' = 'GET_FOUND_ORDER_REQUEST';
export const GET_FOUND_ORDER_SUCCESS: 'GET_FOUND_ORDER_SUCCESS' = 'GET_FOUND_ORDER_SUCCESS';
export const GET_FOUND_ORDER_ERROR: 'GET_FOUND_ORDER_ERROR' = 'GET_FOUND_ORDER_ERROR'